Pin Pydantic to >=1.10.16 and <2
This should fix errors in combination with Python 3.12, e.g. in build
<https://github.com/AKVorrat/dearmep/actions/runs/11783011436/job/32819299151>,
which had:

TypeError: ForwardRef._evaluate() missing 1 required keyword-only argument: 'recursive_guard'

See <https://github.com/pydantic/pydantic/pull/9612>.

This is a minimal change to limit the scope, instead of risking breaking
changes.