Fix TC003
Moving the datetime import in `models.py` into the type checking block
leads to

    pydantic.errors.ConfigError: field "begin" not yet prepared so type
    is still a ForwardRef, you might need to call
    OfficeHoursInterval.update_forward_refs().

so I'm leaving that as is.

Signed-off-by: Tim Weber <scy@scy.name>